<?php

use App\Enums\AgentRunStatus;
use App\Enums\RepoProvider;
use App\Enums\StoryStatus;
use App\Models\AcceptanceCriterion;
use App\Models\AgentRun;
use App\Models\ApprovalPolicy;
use App\Models\Repo;
use App\Models\Subtask;
use App\Models\Task;
use App\Models\Workspace;
use App\Services\ExecutionService;
use App\Services\Executors\Executor;
use App\Services\PullRequests\GithubPullRequestProvider;
use App\Services\WorkspaceRunner;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Symfony\Component\Process\Process;

uses(RefreshDatabase::class);

test('GitHub provider posts the expected payload and returns parsed result', function () {
    Http::fake([
        'api.github.com/repos/datashaman/specify/pulls' => Http::response([
            'html_url' => 'https://github.com/datashaman/specify/pull/42',
            'number' => 42,
            'id' => 12345678,
        ], 201),
    ]);

    $ws = Workspace::factory()->create();
    $repo = Repo::factory()->for($ws)->create([
        'url' => 'https://github.com/datashaman/specify.git',
        'access_token' => 'ghp_secret',
        'default_branch' => 'main',
        'provider' => RepoProvider::Github,
    ]);

    $result = (new GithubPullRequestProvider)->createPullRequest(
        repo: $repo,
        head: 'specify/feat-x',
        base: 'main',
        title: 'Specify: do thing',
        body: 'Generated by agent run',
    );

    expect($result)->toMatchArray([
        'url' => 'https://github.com/datashaman/specify/pull/42',
        'number' => 42,
    ]);

    Http::assertSent(function ($request) {
        $body = $request->data();

        return $request->url() === 'https://api.github.com/repos/datashaman/specify/pulls'
            && $request->hasHeader('Authorization', 'Bearer ghp_secret')
            && $request->hasHeader('Accept', 'application/vnd.github+json')
            && $body['title'] === 'Specify: do thing'
            && $body['head'] === 'specify/feat-x'
            && $body['base'] === 'main';
    });
});

test('GitHub provider parses owner/repo from various URL shapes', function () {
    Http::fake(['*' => Http::response(['html_url' => 'x', 'number' => 1, 'id' => 1])]);

    $ws = Workspace::factory()->create();

    $cases = [
        'https://github.com/owner/repo.git',
        'https://github.com/owner/repo',
    ];

    foreach ($cases as $url) {
        $repo = Repo::factory()->for($ws)->create([
            'url' => $url,
            'access_token' => 'ghp',
            'provider' => RepoProvider::Github,
        ]);
        (new GithubPullRequestProvider)->createPullRequest($repo, 'h', 'b', 't');
    }

    Http::assertSentCount(2);
    Http::assertSent(fn ($r) => str_contains($r->url(), '/owner/repo/pulls'));
});

test('GitHub provider raises when access_token missing', function () {
    $ws = Workspace::factory()->create();
    $repo = Repo::factory()->for($ws)->create([
        'access_token' => null,
        'provider' => RepoProvider::Github,
    ]);

    expect(fn () => (new GithubPullRequestProvider)->createPullRequest($repo, 'h', 'b', 't'))
        ->toThrow(RuntimeException::class, 'access_token');
});

test('GitHub provider surfaces non-2xx responses as exceptions', function () {
    Http::fake([
        '*' => Http::response(['message' => 'Validation Failed'], 422),
    ]);

    $ws = Workspace::factory()->create();
    $repo = Repo::factory()->for($ws)->create([
        'url' => 'https://github.com/o/r.git',
        'access_token' => 'ghp',
        'provider' => RepoProvider::Github,
    ]);

    expect(fn () => (new GithubPullRequestProvider)->createPullRequest($repo, 'h', 'b', 't'))
        ->toThrow(RuntimeException::class, '422');
});

test('Repo::pullRequestProvider returns null for Generic provider', function () {
    $ws = Workspace::factory()->create();
    $repo = Repo::factory()->for($ws)->create(['provider' => RepoProvider::Generic]);
    expect($repo->pullRequestProvider())->toBeNull();
});

test('Repo::pullRequestProvider returns the GitHub driver for github repos', function () {
    $ws = Workspace::factory()->create();
    $repo = Repo::factory()->for($ws)->create(['provider' => RepoProvider::Github]);

    expect($repo->pullRequestProvider())
        ->toBeInstanceOf(GithubPullRequestProvider::class);
});

test('full pipeline records pull_request_error after a non-fatal PR failure on a github repo (ADR-0004)', function () {
    config(['queue.default' => 'sync']);
    config(['specify.executor.default' => 'cli']);

    Http::fake([
        'api.github.com/repos/datashaman/specify/pulls' => Http::response([
            'html_url' => 'https://github.com/datashaman/specify/pull/9',
            'number' => 9,
            'id' => 1,
        ], 201),
    ]);

    // Build a source bare repo on disk.
    $bare = sys_get_temp_dir().'/specify-src-'.uniqid().'.git';
    new Process(['git', 'init', '--bare', '--initial-branch=main', $bare])->mustRun();
    $seed = sys_get_temp_dir().'/specify-seed-'.uniqid();
    File::ensureDirectoryExists($seed);
    new Process(['git', 'init', '--initial-branch=main', $seed])->mustRun();
    File::put($seed.'/README.md', "# hi\n");
    new Process(['git', '-c', 'user.email=t@t', '-c', 'user.name=t', 'add', 'README.md'], $seed)->mustRun();
    new Process(['git', '-c', 'user.email=t@t', '-c', 'user.name=t', 'commit', '-m', 'initial'], $seed)->mustRun();
    new Process(['git', 'remote', 'add', 'origin', 'file://'.$bare], $seed)->mustRun();
    new Process(['git', 'push', 'origin', 'main'], $seed)->mustRun();
    File::deleteDirectory($seed);

    // Fake agent: edits a file.
    $bin = sys_get_temp_dir().'/specify-fake-agent-'.uniqid().'.sh';
    File::put($bin, "#!/usr/bin/env bash\nset -e\necho 'edit' > NEW.md\necho ok\n");
    chmod($bin, 0o755);
    config(['specify.executor.drivers.cli.command' => [$bin]]);
    config(['specify.runs_path' => sys_get_temp_dir().'/specify-runs-'.uniqid()]);
    app()->forgetInstance(WorkspaceRunner::class);
    app()->forgetInstance(Executor::class);

    // Build hierarchy with a Repo whose URL points at github.com (parser-friendly)
    // but whose remote is the local bare path via origin URL — so we override push by
    // attaching the repo with the github URL used by the parser AND wiring the working
    // directory's origin to the bare. Easier: keep file:// URL but use a github-style URL
    // for parsing only by setting a remote_url metadata field is overkill — instead, set
    // the Repo URL to the bare and accept that PR parsing will fail.
    //
    // Cleanest path here: use the bare for cloning AND assert via Http::sent that the
    // fake was called only when URL parses. Since file:// won't parse, we instead cover
    // the github-URL path in the unit tests above. This integration test asserts the
    // manager+job wiring plays nicely when the URL DOES parse, by patching the URL after
    // clone. We do that by setting the Repo URL to a github URL and seeding `origin` of
    // the working dir to the bare manually.
    //
    // Here: just point the Repo URL at the bare and assert pull_request_error captures
    // the parse failure rather than crashing the run.

    $story = makeStory();
    $project = $story->feature->project;
    $workspace = $project->team->workspace;
    $repo = Repo::factory()->for($workspace)->create([
        'url' => 'file://'.$bare,
        'provider' => RepoProvider::Github,
        'default_branch' => 'main',
        'access_token' => 'ghp_fake',
    ]);
    $project->attachRepo($repo);

    ApprovalPolicy::create([
        'scope_type' => ApprovalPolicy::SCOPE_PROJECT,
        'scope_id' => $project->id,
        'required_approvals' => 0,
    ]);

    $ac = $story->acceptanceCriteria()->first() ?? AcceptanceCriterion::factory()->for($story)->create();
    $task = Task::factory()->forCurrentPlanOf($story)->create(['name' => 'add file', 'position' => 0, 'acceptance_criterion_id' => $ac->id]);
    $subtask = Subtask::factory()->for($task)->create(['name' => 'add file', 'position' => 0]);
    $story->forceFill(['status' => StoryStatus::Draft->value])->save();
    $story->fresh()->submitForApproval();
    $task->plan->submitForApproval();
    app(ExecutionService::class)->startStoryExecution($story->fresh());

    $run = AgentRun::where('runnable_id', $subtask->id)
        ->where('runnable_type', Subtask::class)
        ->latest('id')->firstOrFail();

    // ADR-0004: PR-creation failure must be non-fatal. The run is marked
    // Succeeded with the failure stamped on `output.pull_request_error`,
    // and the cascade still advances the Subtask to Done.
    expect($run->status)->toBe(AgentRunStatus::Succeeded)
        ->and($run->output['pull_request_error'] ?? null)->toBeString()
        ->and($run->output['pull_request_error'])->toContain('parse')
        ->and($subtask->fresh()->status->value)->toBe('done');

    @unlink($bin);
    File::deleteDirectory($bare);
    foreach (glob(sys_get_temp_dir().'/specify-runs-*') as $p) {
        File::deleteDirectory($p);
    }
});
